export const myPosts = [
    {
        id: 'm1',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/scene.png',
        postTitle: 'Amazing Scene',
        comments: 23,
        likes: 34,
        location: 'Ivano-Frankivs\'k Region, Ukraine',
    },
    {
        id: 'm2',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/park.png',
        postTitle: 'Park',
        comments: 12,
        likes: 53,
        location: 'Vinnytsia, Ukraine',
    },
    {
        id: 'm3',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/sunset.png',
        postTitle: 'Sunset',
        comments: 15,
        likes: 89,
        location: 'Lviv, Ukraine',
    },
    {
        id: 'm4',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/park.png',
        postTitle: 'Park',
        comments: 12,
        likes: 53,
        location: 'Vinnytsia, Ukraine',
    },
    {
        id: 'm5',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/sunset.png',
        postTitle: 'Sunset',
        comments: 15,
        likes: 89,
        location: 'Lviv, Ukraine',
    },
    {
        id: 'm6',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/park.png',
        postTitle: 'Park',
        comments: 12,
        likes: 53,
        location: 'Vinnytsia, Ukraine',
    },
    {
        id: 'm7',
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/sunset.png',
        postTitle: 'Sunset',
        comments: 15,
        likes: 89,
        location: 'Lviv, Ukraine',
    },
];