export const somePosts = [
    {
        id: 'p1',
        name: 'Millie Brown',
        mail: 'millie@mail.com',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/scene.png',
        postTitle: 'Amazing Scene',
        comments: 23,
        likes: 34,
        location: 'Ivano-Frankivs\'k Region, Ukraine',
    },
    {
        id: 'p2',
        name: 'Bogie Moon',
        mail: 'bmoon@mail.com',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user1.webp",
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/park.png',
        postTitle: 'Park',
        comments: 12,
        likes: 53,
        location: 'Vinnytsia, Ukraine',
    },
    {
        id: 'p3',
        name: 'Ori Fuze',
        mail: 'orifuze@mail.com',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user2.jpg",
        thumbnail: 'https://raw.githubusercontent.com/MaksymKasianchuk/img/main/sunset.png',
        postTitle: 'Sunset',
        comments: 15,
        likes: 89,
        location: 'Lviv, Ukraine',
    },
];