export const someComments = [
    {
        id: 'c1',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        text: 'Really love your most recent photo. I\’ve been trying to capture the same thing for a few months and would love some tips!', 
        meta: '09 июня, 2020 | 08:40',
        type: 'my',
    },
    {
        id: 'c2',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user1.webp",
        text: 'A fast 50mm like f1.8 would help with the bokeh. I\’ve been using primes as they tend to get a bit sharper images.', 
        meta: '09 июня, 2020 | 09:14',
        type: 'another',
    },
    {
        id: 'c3',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        text: 'Thank you! That was very helpful!', 
        meta: '09 июня, 2020 | 09:20',
        type: 'my',
    },
    {
        id: 'c4',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user2.jpg",
        text: 'Thank you to!', 
        meta: '09 июня, 2020 | 09:20',
        type: 'another',
    },
    {
        id: 'c5',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        text: 'Really love your most recent photo. I\’ve been trying to capture the same thing for a few months and would love some tips!', 
        meta: '09 июня, 2020 | 08:40',
        type: 'my',
    },
    {
        id: 'c6',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user1.webp",
        text: 'A fast 50mm like f1.8 would help with the bokeh. I\’ve been using primes as they tend to get a bit sharper images.', 
        meta: '09 июня, 2020 | 09:14',
        type: 'another',
    },
    {
        id: 'c7',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        text: 'Thank you! That was very helpful!', 
        meta: '09 июня, 2020 | 09:20',
        type: 'my',
    },
    {
        id: 'c8',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user2.jpg",
        text: 'Thank you to!', 
        meta: '09 июня, 2020 | 09:20',
        type: 'another',
    },
    {
        id: 'c9',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        text: 'Really love your most recent photo. I\’ve been trying to capture the same thing for a few months and would love some tips!', 
        meta: '09 июня, 2020 | 08:40',
        type: 'my',
    },
    {
        id: 'c10',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user1.webp",
        text: 'A fast 50mm like f1.8 would help with the bokeh. I\’ve been using primes as they tend to get a bit sharper images.', 
        meta: '09 июня, 2020 | 09:14',
        type: 'another',
    },
    {
        id: 'c11',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user.png",
        text: 'Thank you! That was very helpful!', 
        meta: '09 июня, 2020 | 09:20',
        type: 'my',
    },
    {
        id: 'c12',
        avatar: "https://raw.githubusercontent.com/MaksymKasianchuk/img/main/user2.jpg",
        text: 'Thank you to!', 
        meta: '09 июня, 2020 | 09:20',
        type: 'another',
    },
];